### PR TITLE
fix(115): support float QPS

### PR DESCRIPTION
**Pull request by KirCute**
Change the type of `LimitRate` in 115 Cloud and 115 Share from `number` to `float`

### CODE REVIEW

**Comment by KirCute** [comment]
Frontend part AlistGo/alist-web#212

**Review by xhofe — APPROVED** [review]

**Comment by XXX-FILES** [comment]
use  this beta version , PotPlayer can't open playlist 115  folder now, go back to last earlier version it's OK again.

**Comment by KirCute** [comment]
> use  this beta version , PotPlayer can't open playlist 115  folder now, go back to last earlier version it's OK again.

I do not change anything about file transfering. Could it be other reasons that caused this problem?

**Comment by SheltonZhu** [comment]
default field should be 2.0 instead of 2

**Pull request merged**
