### PR TITLE
perf: optimize sqlite3

### PR DESCRIPTION
**Pull request by Aoang**
- use journal mode to WAL
 - set locking mode to EXCLUSIVE
 - set auto vacuum

ref:
 - https://www.sqlite.org/pragma.html#pragma_journal_mode
 - https://www.sqlite.org/pragma.html#pragma_locking_mode
 - https://www.sqlite.org/pragma.html#pragma_auto_vacuum

### CODE REVIEW

**Comment by rayxipad** [comment]
How to reset login password in qnap ?

**Comment by zgxhmj** [comment]
After the Alist service is started manually, you can open the back login page. After entering the user name and password, you can log in normally. After login, Baidu Web disk New, Baidu Web disk old and Ali Cloud disk are displayed. If you enter the user name and password on the login page after the script is automatically started, a message is displayed indicating that the user name and password are incorrect and you cannot log in.

**Comment by jerry34246895** [comment]
qqqqqqqqqqqq

**Comment by johson123456** [comment]
2413262132@qq.com

**Comment by tharus20** [comment]
./alist admin set NEW_PASSWORD

**Comment by Frisus** [comment]
./alist admin

**Comment by ingenhouse** [comment]
./alist admin

**Comment by ingenhouse** [comment]
./alist admin set NEW_PASSWORD

**Comment by Si-Naw** [comment]
./alist admin set NEW_PASSWORD

**Comment by thnglehoang26-source** [comment]
./alist admin set NEW_PASSWORD

**Pull request merged**
